name: mailer ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: jest tests
        working-directory: ./service
        run: |
          echo "${{ secrets.MSMTPRC }}" > msmtprc \
          && docker compose up -d \
          && sleep 5 \
          && docker compose run mailer bash -c "./node_modules/.bin/jest --clearCache && ./node_modules/.bin/jest"
